# Generated by Django 3.2.7 on 2021-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('original_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image_name', models.CharField(max_length=255)),
                ('is_listimage', models.BooleanField(default=True)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
